version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master
      POSTGRES_DB: recipe_db
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/code
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: master
      DB_URL: db:5432
      DB_NAME: recipe_db
